load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/organicveggie/live-shows
# gazelle:resolve proto validate/validate.proto @com_envoyproxy_protoc_gen_validate//validate:validate_proto
# gazelle:resolve proto go validate/validate.proto @com_envoyproxy_protoc_gen_validate//validate:validate_go_proto
gazelle(name = "gazelle")
